#!/bin/sh

borrar()
{
  rm -f *.aux *.toc *.log *.out *.lof
}

rm -rf main.pdf

borrar
cd introduccion
borrar
cd ../bibliografia
borrar
cd ../arquitectura
borrar
cd ../implementacion
borrar

rm -f ../src_tex/*.tex

